### ISSUE TITLE
Latest nirum-python is not compatible with latest nirum.

### ISSUE THREAD

**Issue by Jhuni0123** [spoqa/nirum-python#119]
ex) `nirum.deserialize.deserialize_*`
After nirum 4.0, many fields of nirum objects are removed. https://github.com/nirum-lang/nirum/blob/master/CHANGES.md#python-target-2 
But it still use them.

Tests are also broken after last release.

**Comment by Jhuni0123** [comment]
It seems that this is applied in master branch. It needs to be released.

**Comment by dahlia** [comment]
@kanghyojun We need to release the version 0.7.0…

By the way, I believe we should give org/repo/Hackage/PyPI ownerships to @spoqa people.

**Comment by kanghyojun** [comment]
https://pypi.org/project/nirum/0.7.0/ is just released. And I gave the maintainer role to [dev_spoqa](https://pypi.org/user/dev_spoqa/).
