### ISSUE TITLE
Fails to import typing on Python 3.4

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum-python#17]
It fails to `import typing` on Python 3.4.  I believe nirum-python has to specify an optional dependency on the [typing][1] package if Python 3.4 or below.

[1]: https://pypi.python.org/pypi/typing

**Comment by admire93** [comment]
https://github.com/spoqa/nirum-python/commit/7bef579872e62d2466d254e2c7d10eb69cdd9cd3 fixed
